# Generated by Django 4.2.27 on 2026-01-09 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(default='Swtich_name', max_length=100, verbose_name='스위치 이름')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='관리 IP')),
                ('switch_model', models.CharField(max_length=100, verbose_name='스위치 모델명')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='시리얼 번호')),
            ],
            options={
                'verbose_name_plural': '클러스터 스위치 관리',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='고객사명')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='산업군')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='고객측 담당자')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='연락처')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup', models.CharField(choices=[('AFF', 'AFF'), ('FAS', 'FAS')], max_length=10, verbose_name='라인업')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델명')),
            ],
            options={
                'verbose_name_plural': '장비 모델 관리',
            },
        ),
        migrations.CreateModel(
            name='InstallBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='설치 위치')),
                ('rack_space', models.CharField(max_length=100, verbose_name='상면 번호')),
                ('service_name', models.CharField(max_length=100, verbose_name='서비스명')),
                ('project', models.CharField(max_length=100, verbose_name='프로젝트명')),
                ('is_switch_connected', models.BooleanField(default=False, help_text='스위치와 물리적으로 연결되어 있으면 체크하세요.', verbose_name='클러스터 스위치 연동 여부')),
                ('serial_number_1', models.CharField(max_length=100, verbose_name='시리얼 번호(Node 1)')),
                ('serial_number_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='시리얼 번호(Node 2)')),
                ('cluster_name', models.CharField(max_length=100, verbose_name='Cluster Name')),
                ('ontap_version', models.CharField(max_length=50, verbose_name='ONTAP Version')),
                ('install_date', models.DateField(verbose_name='설치일')),
                ('contract_end_date', models.DateField(verbose_name='백계약 종료일')),
                ('periodic_inspection', models.BooleanField(default=True, verbose_name='정기점검 대상 여부')),
                ('maintenance_start', models.DateField(verbose_name='유지보수 시작일')),
                ('maintenance_end', models.DateField(verbose_name='유지보수 종료일')),
                ('service_level', models.CharField(choices=[('4hr_24x7', '4hr/24x7'), ('NBD', 'Next Business Day'), ('Standard', 'Standard (9x5)')], max_length=20, verbose_name='서비스 레벨')),
                ('license_info', models.TextField(verbose_name='라이센스 정보')),
                ('ip_lists', models.TextField(verbose_name='IP Lists (관리/데이터)')),
                ('shelf_models', models.CharField(max_length=200, verbose_name='Shelf 모델명')),
                ('disk_info', models.TextField(verbose_name='Disk/Shelf 정보 (타입 및 개수)')),
                ('assigned_engineers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='담당 엔지니어')),
                ('cluster_switch_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw1_storages', to='installbase.clusterswitch', verbose_name='클러스터 스위치 #1')),
                ('cluster_switch_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw2_storages', to='installbase.clusterswitch', verbose_name='클러스터 스위치 #2')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='installbase.customer', verbose_name='고객사')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='installbase.product', verbose_name='모델명')),
            ],
            options={
                'verbose_name_plural': 'Install Base 관리',
            },
        ),
        migrations.CreateModel(
            name='ExpansionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansion_date', models.DateField(verbose_name='증설 날짜')),
                ('description', models.TextField(verbose_name='증설 내용 (Disk/Shelf 추가 등)')),
                ('install_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansions', to='installbase.installbase', verbose_name='해당 장비')),
            ],
            options={
                'verbose_name_plural': '증설 이력 관리',
            },
        ),
    ]
