# Generated by Django 4.2.27 on 2026-01-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='industry',
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_logos/', verbose_name='고객사 로고'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='모델 이미지'),
        ),
    ]
