# Generated by Django 4.2.27 on 2026-01-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0002_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='service_level',
            field=models.CharField(choices=[('4HR_NRD', '4HR_NRD'), ('4HR', '4HR'), ('Next Business Day', 'Next Business Day'), ('no_Contract', '미계약')], max_length=20, verbose_name='서비스 레벨'),
        ),
    ]
