# Generated by Django 4.2.27 on 2026-01-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0003_alter_installbase_service_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='controller_slots',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installbase',
            name='license_type',
            field=models.CharField(choices=[('base', 'Base'), ('one', 'ONTAP ONE')], default='base', max_length=10),
        ),
    ]
