# Generated by Django 4.2.27 on 2026-01-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0004_installbase_controller_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='node_name_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='노드1 이름(Node 1)'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='node_name_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='노드2 이름(Node 2)'),
        ),
    ]
