# Generated by Django 4.2.27 on 2026-01-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0005_installbase_node_name_1_installbase_node_name_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='백계약 종료일'),
        ),
    ]
