# Generated by Django 4.2.27 on 2026-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0006_alter_installbase_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='maintenance_end',
            field=models.DateField(blank=True, null=True, verbose_name='유지보수 종료일'),
        ),
    ]
