# Generated by Django 4.2.27 on 2026-01-10 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0007_alter_installbase_maintenance_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installbase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expansionhistory',
            name='description',
            field=models.TextField(verbose_name='증설 내용'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='controller_slots',
            field=models.TextField(blank=True, null=True, verbose_name='컨트롤러 슬롯'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='disk_info',
            field=models.TextField(blank=True, verbose_name='Disk/Shelf 정보 (타입 및 개수)'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='ip_lists',
            field=models.TextField(blank=True, verbose_name='IP Lists (관리/데이터)'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='is_switch_connected',
            field=models.BooleanField(default=False, verbose_name='클러스터 스위치 연동 여부'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='license_info',
            field=models.TextField(blank=True, verbose_name='라이센스 정보'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='license_type',
            field=models.CharField(choices=[('base', 'Base'), ('one', 'ONTAP ONE')], default='base', max_length=10, verbose_name='라이선스 타입'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='periodic_inspection',
            field=models.CharField(choices=[('none', '비대상'), ('monthly', '월점검'), ('quarter', '분기점검'), ('half', '반기점검')], default='none', max_length=20, verbose_name='정기점검 주기'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='rack_space',
            field=models.CharField(blank=True, max_length=100, verbose_name='상면 번호'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='shelf_models',
            field=models.CharField(blank=True, max_length=200, verbose_name='Shelf 모델명'),
        ),
    ]
