# Generated by Django 4.2.27 on 2026-01-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0008_installbase_created_at_installbase_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='country',
            field=models.CharField(choices=[('KR', 'South Korea'), ('US', 'United States'), ('CN', 'China'), ('DE', 'Germany'), ('SK', 'Slovakia'), ('IN', 'India'), ('SG', 'Singapore')], default='KR', max_length=2, verbose_name='설치 국가'),
        ),
    ]
