# Generated by Django 4.2.27 on 2026-01-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0009_installbase_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterswitch',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='백계약 종료일'),
        ),
    ]
