# Generated by Django 4.2.27 on 2026-01-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0010_clusterswitch_contract_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
    ]
