# Generated by Django 4.2.27 on 2026-01-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0011_installbase_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='node_number_1',
            field=models.IntegerField(blank=True, help_text='1-40', null=True, verbose_name='클러스터 내 노드 번호(Node 1)'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='node_number_2',
            field=models.IntegerField(blank=True, help_text='1-40', null=True, verbose_name='클러스터 내 노드 번호(Node 2)'),
        ),
    ]
