# Generated by Django 4.2.27 on 2026-01-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0012_installbase_node_number_1_installbase_node_number_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='스위치 모델명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='switch_images/', verbose_name='모델 이미지')),
            ],
            options={
                'verbose_name_plural': '스위치 모델 관리',
            },
        ),
        migrations.RemoveField(
            model_name='clusterswitch',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='clusterswitch',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='clusterswitch',
            name='switch_model',
        ),
        migrations.RemoveField(
            model_name='clusterswitch',
            name='switch_name',
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='ip_address_1',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='관리 IP #1'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='ip_address_2',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='관리 IP #2'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='serial_number_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시리얼 번호 #1'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='serial_number_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시리얼 번호 #2'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_name_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스위치 이름 #1'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_name_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스위치 이름 #2'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_model_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='switches_1', to='installbase.switchmodel', verbose_name='스위치 모델 #1'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_model_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='switches_2', to='installbase.switchmodel', verbose_name='스위치 모델 #2'),
        ),
    ]
