# Generated by Django 4.2.27 on 2026-01-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0013_switchmodel_remove_clusterswitch_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterswitch',
            name='serial_number_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시리얼 번호 #1'),
        ),
        migrations.AlterField(
            model_name='clusterswitch',
            name='serial_number_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시리얼 번호 #2'),
        ),
        migrations.AlterField(
            model_name='clusterswitch',
            name='switch_model_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='switches_1', to='installbase.switchmodel', verbose_name='스위치 모델 #1'),
        ),
        migrations.AlterField(
            model_name='clusterswitch',
            name='switch_model_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='switches_2', to='installbase.switchmodel', verbose_name='스위치 모델 #2'),
        ),
        migrations.AlterField(
            model_name='clusterswitch',
            name='switch_name_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스위치 이름 #1'),
        ),
        migrations.AlterField(
            model_name='clusterswitch',
            name='switch_name_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스위치 이름 #2'),
        ),
    ]
