# Generated by Django 4.2.27 on 2026-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0014_alter_clusterswitch_serial_number_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='switch_images/', verbose_name='후면 이미지'),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='switch_images/', verbose_name='전면 이미지'),
        ),
    ]
