# Generated by Django 4.2.27 on 2026-01-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0015_remove_switchmodel_image_switchmodel_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterswitch',
            name='install_date',
            field=models.DateField(blank=True, null=True, verbose_name='설치일'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='maintenance_end',
            field=models.DateField(blank=True, null=True, verbose_name='유지보수 종료일'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='maintenance_start',
            field=models.DateField(blank=True, null=True, verbose_name='유지보수 시작일'),
        ),
    ]
