# Generated by Django 4.2.27 on 2026-01-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0016_clusterswitch_install_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installbase',
            name='cluster_switch_1',
        ),
        migrations.RemoveField(
            model_name='installbase',
            name='cluster_switch_2',
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_type',
            field=models.CharField(choices=[('cluster', 'Cluster Switch'), ('fabric_pool', 'Fabric Pool Switch')], default='cluster', max_length=20, verbose_name='스위치 타입'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='cluster_switch',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted_at__isnull': True, 'switch_type': 'cluster'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_storages', to='installbase.clusterswitch', verbose_name='클러스터 스위치'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='fabric_pool_switch',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted_at__isnull': True, 'switch_type': 'fabric_pool'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_pool_storages', to='installbase.clusterswitch', verbose_name='Fabric Pool 스위치'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='is_fabric_pool_connected',
            field=models.BooleanField(default=False, verbose_name='Fabric Pool 연동 여부'),
        ),
    ]
