# Generated by Django 4.2.27 on 2026-01-13 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('installbase', '0017_remove_installbase_cluster_switch_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('part_replacement', '단순 파트 교체'), ('service_outage', '서비스 장애'), ('issue', '이슈')], max_length=20, verbose_name='이슈 타입')),
                ('issue_date', models.DateField(verbose_name='이슈 발생 일자')),
                ('status', models.CharField(choices=[('open', '진행중'), ('resolved', '해결됨'), ('closed', '종료')], default='open', max_length=20, verbose_name='진행 상태')),
                ('title', models.CharField(max_length=200, verbose_name='이슈 제목')),
                ('content', models.TextField(verbose_name='이슈 내용')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='이슈 종료일')),
                ('case_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='케이스 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='이슈 진행자')),
                ('target_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='installbase.installbase', verbose_name='대상 클러스터')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_issues', to='installbase.installbase', verbose_name='대상 노드')),
            ],
            options={
                'verbose_name_plural': '이슈 관리',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='파트 넘버')),
                ('category', models.CharField(choices=[('node', 'Node'), ('shelf', 'Shelf'), ('disk', 'Disk')], max_length=20, verbose_name='파트 종류')),
                ('part_type', models.CharField(max_length=50, verbose_name='파트 타입')),
                ('description', models.TextField(blank=True, verbose_name='파트 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '파트 관리',
            },
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_quantity', models.IntegerField(default=1, verbose_name='RMA 수량')),
                ('rma_number', models.CharField(max_length=100, verbose_name='RMA 번호')),
                ('return_required', models.CharField(choices=[('required', '반납 필요'), ('not_required', '반납 불필요')], default='required', max_length=20, verbose_name='반납 필요 여부')),
                ('part_quantity', models.IntegerField(default=1, verbose_name='파트 수량')),
                ('delivery_region', models.CharField(max_length=200, verbose_name='배송 지역')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='배송 일자')),
                ('return_region', models.CharField(blank=True, max_length=200, null=True, verbose_name='반납 지역')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='반납 일자')),
                ('is_delayed', models.CharField(choices=[('delayed', '지연배송'), ('normal', '정상배송')], default='normal', max_length=20, verbose_name='지연 배송 여부')),
                ('return_status', models.CharField(choices=[('returned', '반납'), ('not_returned', '미반납')], default='not_returned', max_length=20, verbose_name='반납 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('case_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rmas', to='installbase.issue', verbose_name='케이스 번호')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='installbase.part', verbose_name='파트 넘버')),
            ],
            options={
                'verbose_name_plural': 'RMA 관리',
            },
        ),
    ]
