# Generated by Django 4.2.27 on 2026-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0018_issue_part_rma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='maintenance_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
