# Generated by Django 4.2.27 on 2026-01-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0019_alter_installbase_maintenance_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='maintenance_end',
            field=models.DateField(blank=True, null=True, verbose_name='유지보수 종료일'),
        ),
    ]
