# Generated by Django 4.2.27 on 2026-01-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0020_alter_installbase_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installbase',
            name='cluster_mgmt_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Cluster Management IP'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='node1_bmc_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='첫번째 노드 BMC IP'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='node1_mgmt_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='첫번째 노드 Management IP'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='node2_bmc_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='두번째 노드 BMC IP'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='node2_mgmt_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='두번째 노드 Management IP'),
        ),
        migrations.AddField(
            model_name='installbase',
            name='other_ips',
            field=models.TextField(blank=True, verbose_name='그 외 IP'),
        ),
    ]
