# Generated by Django 4.2.27 on 2026-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0021_installbase_cluster_mgmt_ip_installbase_node1_bmc_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rma',
            name='return_status',
            field=models.CharField(choices=[('returned', '반납'), ('not_returned', '미반납'), ('not_required', '반납 불필요')], default='not_returned', max_length=20, verbose_name='반납 여부'),
        ),
    ]
