# Generated by Django 4.2.27 on 2026-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0022_alter_rma_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', '진행중'), ('closed', '종료')], default='open', max_length=20, verbose_name='진행 상태'),
        ),
    ]
