# Generated by Django 4.2.27 on 2026-01-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0023_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rma',
            name='is_delayed',
            field=models.CharField(choices=[('not_delivered', '배송 미완료'), ('delayed', '지연배송'), ('normal', '정상배송')], default='not_delivered', max_length=20, verbose_name='지연 배송 여부'),
        ),
    ]
