# Generated by Django 4.2.27 on 2026-01-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0024_alter_rma_is_delayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='target_node_number',
            field=models.IntegerField(blank=True, help_text='1 또는 2 (node_name_1 또는 node_name_2)', null=True, verbose_name='대상 노드 번호'),
        ),
    ]
