# Generated by Django 4.2.27 on 2026-01-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0025_issue_target_node_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('진행중', '진행중'), ('종료', '종료')], default='open', max_length=20, verbose_name='진행 상태'),
        ),
    ]
