# Generated by Django 4.2.27 on 2026-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0026_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스위치 버전'),
        ),
    ]
