# Generated by Django 4.2.27 on 2026-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0027_clusterswitch_switch_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterswitch',
            name='switch_version',
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_version_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스위치 버전 #1'),
        ),
        migrations.AddField(
            model_name='clusterswitch',
            name='switch_version_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스위치 버전 #2'),
        ),
    ]
