# Generated by Django 4.2.27 on 2026-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0028_remove_clusterswitch_switch_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='cluster_mgmt_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cluster Management IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node1_bmc_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='첫번째 노드 BMC IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node1_mgmt_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='첫번째 노드 Management IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node2_bmc_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='두번째 노드 BMC IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node2_mgmt_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='두번째 노드 Management IP'),
        ),
    ]
