# Generated by Django 4.2.27 on 2026-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0029_alter_installbase_cluster_mgmt_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='other_ips',
            field=models.TextField(blank=True, null=True, verbose_name='그 외 IP'),
        ),
    ]
