# Generated by Django 4.2.27 on 2026-01-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0030_alter_installbase_other_ips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='project',
            field=models.CharField(max_length=200, verbose_name='프로젝트명'),
        ),
    ]
