# Generated by Django 4.2.27 on 2026-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0032_alter_installbase_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterswitch',
            name='switch_version_1',
        ),
        migrations.RemoveField(
            model_name='clusterswitch',
            name='switch_version_2',
        ),
        migrations.AlterField(
            model_name='installbase',
            name='cluster_mgmt_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Cluster Management IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node1_bmc_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='첫번째 노드 BMC IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node1_mgmt_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='첫번째 노드 Management IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node2_bmc_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='두번째 노드 BMC IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node2_mgmt_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='두번째 노드 Management IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='project',
            field=models.CharField(max_length=100, verbose_name='프로젝트명'),
        ),
    ]
