# Generated by Django 4.2.27 on 2026-01-17 17:44

from django.db import migrations, models


def convert_ip_fields_to_text(apps, schema_editor):
    """IP 필드의 데이터를 텍스트로 변환"""
    InstallBase = apps.get_model('installbase', 'InstallBase')
    db_alias = schema_editor.connection.alias
    
    # 데이터베이스 연결 확인
    try:
        # Django ORM을 사용하여 안전하게 데이터 변환
        ip_fields = ['cluster_mgmt_ip', 'node1_mgmt_ip', 'node2_mgmt_ip', 'node1_bmc_ip', 'node2_bmc_ip']
        
        # 각 InstallBase 레코드를 순회하며 변환
        for installbase in InstallBase.objects.using(db_alias).all():
            for field_name in ip_fields:
                value = getattr(installbase, field_name, None)
                if value:
                    try:
                        # GenericIPAddressField 값을 문자열로 변환
                        str_value = str(value)
                        setattr(installbase, field_name, str_value)
                    except Exception as e:
                        # 변환 실패 시 NULL로 설정
                        setattr(installbase, field_name, None)
            
            # 변경사항 저장
            try:
                installbase.save(update_fields=ip_fields, using=db_alias)
            except Exception as e:
                # 저장 실패 시 스킵
                print(f"Warning: Could not save {installbase.id}: {e}")
                pass
    except Exception as e:
        # 데이터베이스가 비어있거나 다른 문제가 있는 경우 그냥 넘어감
        print(f"Warning: Could not convert IP fields: {e}")
        pass


def reverse_convert_ip_fields(apps, schema_editor):
    """역변환 함수 (CharField -> GenericIPAddressField로 돌아갈 때)"""
    # SQL을 직접 사용하여 유효하지 않은 IP 데이터를 NULL로 설정
    # CharField에서 GenericIPAddressField로 돌아갈 때는 유효한 IP 형식만 유지
    with schema_editor.connection.cursor() as cursor:
        ip_fields = ['cluster_mgmt_ip', 'node1_mgmt_ip', 'node2_mgmt_ip', 'node1_bmc_ip', 'node2_bmc_ip']
        
        for field_name in ip_fields:
            try:
                # 유효한 IP 형식이 아닌 데이터를 NULL로 설정
                # PostgreSQL 정규식 패턴으로 유효한 IP 형식만 매칭
                cursor.execute(f"""
                    UPDATE installbase_installbase 
                    SET {field_name} = NULL
                    WHERE {field_name} IS NOT NULL 
                    AND {field_name}::text !~ '^([0-9]{{1,3}}\\.){{3}}[0-9]{{1,3}}$'
                """)
            except Exception as e:
                # 에러 발생 시 해당 필드를 모두 NULL로 설정
                print(f"Error in reverse conversion for {field_name}: {e}")
                try:
                    cursor.execute(f"""
                        UPDATE installbase_installbase 
                        SET {field_name} = NULL
                        WHERE {field_name} IS NOT NULL
                    """)
                except:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0033_remove_clusterswitch_switch_version_1_and_more'),
    ]

    operations = [
        # 필드 타입 변경 (데이터가 비어있거나 이미 정리된 경우)
        migrations.AlterField(
            model_name='installbase',
            name='cluster_mgmt_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cluster Management IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node1_bmc_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='첫번째 노드 BMC IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node1_mgmt_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='첫번째 노드 Management IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node2_bmc_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='두번째 노드 BMC IP'),
        ),
        migrations.AlterField(
            model_name='installbase',
            name='node2_mgmt_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='두번째 노드 Management IP'),
        ),
    ]
