# Generated by Django 4.2.27 on 2026-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0035_fix_ip_fields_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installbase',
            name='project',
            field=models.CharField(max_length=255, verbose_name='프로젝트명'),
        ),
    ]
