# Generated by Django 4.2.27 on 2026-01-19 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('installbase', '0036_alter_installbase_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resigned', models.BooleanField(default=False, verbose_name='퇴사 여부')),
                ('resigned_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '사용자 프로필',
            },
        ),
    ]
