# Generated by Django 4.2.27 on 2026-01-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0037_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
