# Generated by Django 4.2.27 on 2026-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0038_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetAppAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntap_uid', models.CharField(blank=True, max_length=100, verbose_name='NTAP UID')),
                ('client_id', models.CharField(blank=True, max_length=200, verbose_name='CLIENT ID')),
                ('client_secret', models.CharField(blank=True, max_length=500, verbose_name='CLIENT SECRET')),
                ('last_test_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='마지막 테스트 시리얼 번호')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='마지막 테스트 일시')),
                ('last_test_result', models.TextField(blank=True, null=True, verbose_name='마지막 테스트 결과')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NetApp API 설정',
                'verbose_name_plural': 'NetApp API 설정',
            },
        ),
        migrations.AddField(
            model_name='installbase',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='워런티 종료일'),
        ),
    ]
