# Generated by Django 4.2.27 on 2026-01-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installbase', '0039_netappapiconfig_installbase_warranty_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installbase',
            name='warranty_end_date',
        ),
    ]
