from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from installbase import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.dashboard, name='dashboard'),
    path('installbase/', views.installbase_list, name='installbase_list'),
    path('installbase/create/', views.installbase_create, name='installbase_create'),
    path('installbase/<int:pk>/', views.installbase_detail, name='installbase_detail'),
    path('installbase/<int:pk>/update/', views.InstallBaseUpdateView.as_view(), name='installbase_update'),
    path('installbase/<int:pk>/delete/', views.installbase_delete, name='installbase_delete'),
    path('installbase/<int:pk>/restore/', views.installbase_restore, name='installbase_restore'),
    path('installbase/deleted/', views.installbase_deleted_list, name='installbase_deleted_list'),
    path('clusterswitch/', views.clusterswitch_list, name='clusterswitch_list'),
    path('clusterswitch/create/', views.clusterswitch_create, name='clusterswitch_create'),
    path('clusterswitch/<int:pk>/update/', views.clusterswitch_update, name='clusterswitch_update'),
    path('clusterswitch/<int:pk>/delete/', views.clusterswitch_delete, name='clusterswitch_delete'),
    path('clusterswitch/<int:pk>/restore/', views.clusterswitch_restore, name='clusterswitch_restore'),
    path('clusterswitch/deleted/', views.clusterswitch_deleted_list, name='clusterswitch_deleted_list'),
    path('issue/', views.issue_list, name='issue_list'),
    path('issue/create/', views.issue_create, name='issue_create'),
    path('issue/<int:pk>/', views.issue_detail, name='issue_detail'),
    path('issue/<int:pk>/update/', views.issue_update, name='issue_update'),
    path('issue/<int:pk>/delete/', views.issue_delete, name='issue_delete'),
    path('issue/<int:pk>/restore/', views.issue_restore, name='issue_restore'),
    path('issue/<int:pk>/complete/', views.issue_complete, name='issue_complete'),
    path('issue/deleted/', views.issue_deleted_list, name='issue_deleted_list'),
    path('rma/', views.rma_list, name='rma_list'),
    path('rma/create/', views.rma_create, name='rma_create'),
    path('rma/<int:pk>/update/', views.rma_update, name='rma_update'),
    path('rma/<int:pk>/delete/', views.rma_delete, name='rma_delete'),
    path('rma/<int:pk>/restore/', views.rma_restore, name='rma_restore'),
    path('rma/<int:pk>/delivery/', views.rma_delivery, name='rma_delivery'),
    path('rma/<int:pk>/return/', views.rma_return, name='rma_return'),
    path('rma/deleted/', views.rma_deleted_list, name='rma_deleted_list'),
    path('netapp-api/', views.netapp_api_management, name='netapp_api_management'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('export/installbase/', views.export_installbase_excel, name='export_installbase_excel'),
    path('export/switches/', views.export_switches_excel, name='export_switches_excel'),
    path('export/issues/', views.export_issues_excel, name='export_issues_excel'),
    path('export/rma/', views.export_rma_excel, name='export_rma_excel'),
    path('ajax/add-customer/', views.add_customer_ajax, name='add_customer_ajax'),
    path('ajax/add-product/', views.add_product_ajax, name='add_product_ajax'),
    path('ajax/get-image-url/', views.get_image_url, name='get_image_url'),
    path('ajax/get-available-node-numbers/', views.get_available_node_numbers, name='get_available_node_numbers'),
    path('ajax/add-expansion/<int:pk>/', views.add_expansion_ajax, name='add_expansion_ajax'),
    path('ajax/edit-expansion/<int:pk>/', views.edit_expansion_ajax, name='edit_expansion_ajax'),
    path('ajax/delete-expansion/<int:pk>/', views.delete_expansion_ajax, name='delete_expansion_ajax'),
    path('ajax/add-switch-model/', views.add_switch_model_ajax, name='add_switch_model_ajax'),
    path('ajax/add-part/', views.add_part_ajax, name='add_part_ajax'),
    path('ajax/get-parts-by-category/', views.get_parts_by_category_ajax, name='get_parts_by_category_ajax'),
    path('ajax/get-cluster-nodes/', views.get_cluster_nodes_ajax, name='get_cluster_nodes_ajax'),
    path('ajax/get-clusters/', views.get_clusters_ajax, name='get_clusters_ajax'),
    path('ajax/get-customers/', views.get_customers_ajax, name='get_customers_ajax'),
    path('ajax/get-nodes-by-cluster/', views.get_nodes_by_cluster_ajax, name='get_nodes_by_cluster_ajax'),
    path('ajax/get-node-info/', views.get_node_info_ajax, name='get_node_info_ajax'),
    path('ajax/get-cases/', views.get_cases_ajax, name='get_cases_ajax'),
    path('ajax/get-issues-api/', views.get_issues_api, name='get_issues_api'),
    path('ajax/clusterswitch/<int:pk>/storages/', views.clusterswitch_storages, name='clusterswitch_storages'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
